//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arriendojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALQUILER
    {
        public int ID { get; set; }
        public int ID_LIBRO { get; set; }
        public int ID_USUARIO { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime FECHAALQUILER { get; set; }
        public string INFORMACION { get; set; }
        public System.DateTime FECHATERMINO { get; set; }
        public string ESTADO { get; set; }
        public int ID_TRANSACCION { get; set; }
    
        public virtual LIBRO_CARRITO_USUARIO LIBRO_CARRITO_USUARIO { get; set; }
        public virtual TRANSACCION TRANSACCION { get; set; }
    }
}
