//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arriendojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALQUILA
    {
        public int ID_LIBRO { get; set; }
        public int ID_PERSONA { get; set; }
        public int ID_FECHA { get; set; }
        public System.DateTime FECHAFIN { get; set; }
        public decimal TOTAL { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual FECHAALQUILER FECHAALQUILER { get; set; }
        public virtual LIBRO LIBRO { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
