//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arriendojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int ID { get; set; }
        public Nullable<int> ID_TRANSACCION { get; set; }
        public string DETALLES { get; set; }
        public System.DateTime FECHAEMISION { get; set; }
    
        public virtual TRANSACCION TRANSACCION { get; set; }
    }
}
