//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arriendojuegos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class arriendojuegosEntities1 : DbContext
    {
        public arriendojuegosEntities1()
            : base("name=arriendojuegosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<ALQUILER> ALQUILER { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<EDITORIAL> EDITORIAL { get; set; }
        public virtual DbSet<FECHAALQUILER> FECHAALQUILER { get; set; }
        public virtual DbSet<LIBRO> LIBRO { get; set; }
        public virtual DbSet<LIBRO_CARRITO_USUARIO> LIBRO_CARRITO_USUARIO { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    
        [DbFunction("arriendojuegosEntities1", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[arriendojuegosEntities1].[SplitString](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual int ACTUALIZARLIBRO(string iSBN, string nOMBRE, string aUTOR, string tIPOLIBRO, Nullable<decimal> pRECIO, Nullable<int> sTOCK, Nullable<int> aNIO, Nullable<int> eDITORIAL, Nullable<int> iD_ADMINISTRADOR, string dESCRIPCION, Nullable<int> iDLIBRO, string cATEGORIAS_ID_LIST, string iMAGEN)
        {
            var iSBNParameter = iSBN != null ?
                new ObjectParameter("ISBN", iSBN) :
                new ObjectParameter("ISBN", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aUTORParameter = aUTOR != null ?
                new ObjectParameter("AUTOR", aUTOR) :
                new ObjectParameter("AUTOR", typeof(string));
    
            var tIPOLIBROParameter = tIPOLIBRO != null ?
                new ObjectParameter("TIPOLIBRO", tIPOLIBRO) :
                new ObjectParameter("TIPOLIBRO", typeof(string));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(int));
    
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            var eDITORIALParameter = eDITORIAL.HasValue ?
                new ObjectParameter("EDITORIAL", eDITORIAL) :
                new ObjectParameter("EDITORIAL", typeof(int));
    
            var iD_ADMINISTRADORParameter = iD_ADMINISTRADOR.HasValue ?
                new ObjectParameter("ID_ADMINISTRADOR", iD_ADMINISTRADOR) :
                new ObjectParameter("ID_ADMINISTRADOR", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var iDLIBROParameter = iDLIBRO.HasValue ?
                new ObjectParameter("IDLIBRO", iDLIBRO) :
                new ObjectParameter("IDLIBRO", typeof(int));
    
            var cATEGORIAS_ID_LISTParameter = cATEGORIAS_ID_LIST != null ?
                new ObjectParameter("CATEGORIAS_ID_LIST", cATEGORIAS_ID_LIST) :
                new ObjectParameter("CATEGORIAS_ID_LIST", typeof(string));
    
            var iMAGENParameter = iMAGEN != null ?
                new ObjectParameter("IMAGEN", iMAGEN) :
                new ObjectParameter("IMAGEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZARLIBRO", iSBNParameter, nOMBREParameter, aUTORParameter, tIPOLIBROParameter, pRECIOParameter, sTOCKParameter, aNIOParameter, eDITORIALParameter, iD_ADMINISTRADORParameter, dESCRIPCIONParameter, iDLIBROParameter, cATEGORIAS_ID_LISTParameter, iMAGENParameter);
        }
    
        public virtual int CREARADMIN(string nOMBRE, string cORREO, string cONTRASEÑA, string sALT)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            var sALTParameter = sALT != null ?
                new ObjectParameter("SALT", sALT) :
                new ObjectParameter("SALT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARADMIN", nOMBREParameter, cORREOParameter, cONTRASEÑAParameter, sALTParameter);
        }
    
        public virtual int CREARUSUARIO(string nOMBRE, string cORREO, string cONTRASEÑA, Nullable<int> tELEFONO, Nullable<int> sEXO, Nullable<System.DateTime> fECHANACIMIENTO, Nullable<int> cOMUNA, string dIRECCION, string sALT)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(int));
    
            var sEXOParameter = sEXO.HasValue ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(int));
    
            var fECHANACIMIENTOParameter = fECHANACIMIENTO.HasValue ?
                new ObjectParameter("FECHANACIMIENTO", fECHANACIMIENTO) :
                new ObjectParameter("FECHANACIMIENTO", typeof(System.DateTime));
    
            var cOMUNAParameter = cOMUNA.HasValue ?
                new ObjectParameter("COMUNA", cOMUNA) :
                new ObjectParameter("COMUNA", typeof(int));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var sALTParameter = sALT != null ?
                new ObjectParameter("SALT", sALT) :
                new ObjectParameter("SALT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARUSUARIO", nOMBREParameter, cORREOParameter, cONTRASEÑAParameter, tELEFONOParameter, sEXOParameter, fECHANACIMIENTOParameter, cOMUNAParameter, dIRECCIONParameter, sALTParameter);
        }
    
        public virtual int DELETEBOOK(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEBOOK", iDParameter);
        }
    
        public virtual int DELETEUSUARIO(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEUSUARIO", iDParameter);
        }
    
        public virtual ObjectResult<DESPLEGARCOMUNAS_Result> DESPLEGARCOMUNAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DESPLEGARCOMUNAS_Result>("DESPLEGARCOMUNAS");
        }
    
        public virtual ObjectResult<DESPLEGARSEXO_Result> DESPLEGARSEXO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DESPLEGARSEXO_Result>("DESPLEGARSEXO");
        }
    
        public virtual ObjectResult<Nullable<int>> GETID(string cORREO)
        {
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GETID", cORREOParameter);
        }
    
        public virtual ObjectResult<INICIOSESION_Result> INICIOSESION(string cORREO)
        {
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INICIOSESION_Result>("INICIOSESION", cORREOParameter);
        }
    
        public virtual ObjectResult<OBTENERCATEGORIAS_Result> OBTENERCATEGORIAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OBTENERCATEGORIAS_Result>("OBTENERCATEGORIAS");
        }
    
        public virtual ObjectResult<OBTENEREDITORIAL_Result> OBTENEREDITORIAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OBTENEREDITORIAL_Result>("OBTENEREDITORIAL");
        }
    
        public virtual ObjectResult<OBTENERLIBRO_Result> OBTENERLIBRO(Nullable<int> iD, string tIPO_LIBRO, Nullable<int> cATEGORIA_ID, Nullable<int> aNIO)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tIPO_LIBROParameter = tIPO_LIBRO != null ?
                new ObjectParameter("TIPO_LIBRO", tIPO_LIBRO) :
                new ObjectParameter("TIPO_LIBRO", typeof(string));
    
            var cATEGORIA_IDParameter = cATEGORIA_ID.HasValue ?
                new ObjectParameter("CATEGORIA_ID", cATEGORIA_ID) :
                new ObjectParameter("CATEGORIA_ID", typeof(int));
    
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OBTENERLIBRO_Result>("OBTENERLIBRO", iDParameter, tIPO_LIBROParameter, cATEGORIA_IDParameter, aNIOParameter);
        }
    
        public virtual ObjectResult<OBTENERLIBROSINDEX_Result> OBTENERLIBROSINDEX(Nullable<int> iD, string tIPO_LIBRO, Nullable<int> cATEGORIA_ID, Nullable<int> aNIO)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tIPO_LIBROParameter = tIPO_LIBRO != null ?
                new ObjectParameter("TIPO_LIBRO", tIPO_LIBRO) :
                new ObjectParameter("TIPO_LIBRO", typeof(string));
    
            var cATEGORIA_IDParameter = cATEGORIA_ID.HasValue ?
                new ObjectParameter("CATEGORIA_ID", cATEGORIA_ID) :
                new ObjectParameter("CATEGORIA_ID", typeof(int));
    
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OBTENERLIBROSINDEX_Result>("OBTENERLIBROSINDEX", iDParameter, tIPO_LIBROParameter, cATEGORIA_IDParameter, aNIOParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> OBTENERROL(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("OBTENERROL", iDParameter);
        }
    
        public virtual ObjectResult<OBTENERUSUARIOID_Result> OBTENERUSUARIOID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OBTENERUSUARIOID_Result>("OBTENERUSUARIOID", iDParameter);
        }
    
        public virtual ObjectResult<OBTENERUSUARIOS_Result> OBTENERUSUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OBTENERUSUARIOS_Result>("OBTENERUSUARIOS");
        }
    
        public virtual int REGISTRARLIBRO(string iSBN, string nOMBRE, string aUTOR, string tIPOLIBRO, Nullable<decimal> pRECIO, Nullable<int> sTOCK, Nullable<int> aNIO, Nullable<int> eDITORIAL, Nullable<int> iD_ADMINISTRADOR, string dESCRIPCION, ObjectParameter iDLIBRO, string cATEGORIAS_ID_LIST, string iMAGEN)
        {
            var iSBNParameter = iSBN != null ?
                new ObjectParameter("ISBN", iSBN) :
                new ObjectParameter("ISBN", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aUTORParameter = aUTOR != null ?
                new ObjectParameter("AUTOR", aUTOR) :
                new ObjectParameter("AUTOR", typeof(string));
    
            var tIPOLIBROParameter = tIPOLIBRO != null ?
                new ObjectParameter("TIPOLIBRO", tIPOLIBRO) :
                new ObjectParameter("TIPOLIBRO", typeof(string));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(int));
    
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            var eDITORIALParameter = eDITORIAL.HasValue ?
                new ObjectParameter("EDITORIAL", eDITORIAL) :
                new ObjectParameter("EDITORIAL", typeof(int));
    
            var iD_ADMINISTRADORParameter = iD_ADMINISTRADOR.HasValue ?
                new ObjectParameter("ID_ADMINISTRADOR", iD_ADMINISTRADOR) :
                new ObjectParameter("ID_ADMINISTRADOR", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var cATEGORIAS_ID_LISTParameter = cATEGORIAS_ID_LIST != null ?
                new ObjectParameter("CATEGORIAS_ID_LIST", cATEGORIAS_ID_LIST) :
                new ObjectParameter("CATEGORIAS_ID_LIST", typeof(string));
    
            var iMAGENParameter = iMAGEN != null ?
                new ObjectParameter("IMAGEN", iMAGEN) :
                new ObjectParameter("IMAGEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REGISTRARLIBRO", iSBNParameter, nOMBREParameter, aUTORParameter, tIPOLIBROParameter, pRECIOParameter, sTOCKParameter, aNIOParameter, eDITORIALParameter, iD_ADMINISTRADORParameter, dESCRIPCIONParameter, iDLIBRO, cATEGORIAS_ID_LISTParameter, iMAGENParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UPDATEUSUARIO(Nullable<int> iD, string nOMBRE, string cORREO, Nullable<int> tELEFONO, string dIRECCION, Nullable<int> cOMUNA)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(int));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cOMUNAParameter = cOMUNA.HasValue ?
                new ObjectParameter("COMUNA", cOMUNA) :
                new ObjectParameter("COMUNA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATEUSUARIO", iDParameter, nOMBREParameter, cORREOParameter, tELEFONOParameter, dIRECCIONParameter, cOMUNAParameter);
        }
    }
}
