//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arriendojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.ALQUILA = new HashSet<ALQUILA>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> sexo { get; set; }
        public System.DateTime FECHANACIMIENTO { get; set; }
        public int COMUNA { get; set; }
        public string DIRECCION { get; set; }
        public string SALT { get; set; }
        public string CONTRASEÑA { get; set; }
        public string ROL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALQUILA> ALQUILA { get; set; }
        public virtual COMUNA COMUNA1 { get; set; }
        public virtual sexo sexo1 { get; set; }
    }
}
